"""XLM-R based anomaly token detection module.

This module provides standard wrappers and class structures around the fine-tuned
XLM-RoBERTa Token Classification model to detect non-standard/noise tokens
(class 1) in social media sentences across different languages.

It defines language-specific probability thresholds to balance precision and
recall when classifying tokens as standard (0) or non-standard/noise (1).
"""

from __future__ import annotations

import torch
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    Trainer,
    TrainingArguments,
    DataCollatorForTokenClassification,
)
from typing import List, Tuple, Dict, Any, Sequence, Union

# Language-specific token detection thresholds.
# Optima resolved via mini-validation grid search or linguistic categories.
LANG_DETECTION_THRESHOLDS: Dict[str, float] = {
    "ko": 0.55,
    "en": 0.85,
    "iden": 0.90,
    "ja": 0.85,
    "tr": 0.85,
    "zh": 0.85,
    "hr": 0.75,
    "sr": 0.75,
    "da": 0.75,
    "bs": 0.75,
    "ru": 0.75,
    "es": 0.60,
    "it": 0.60,
    "de": 0.60,
}
DEFAULT_DETECTION_THRESHOLD: float = 0.60


def get_lang_threshold(lang: str) -> float:
    """Retrieves the detection probability threshold for a given language code.

    Args:
        lang: The ISO language code or identifier string.

    Returns:
        float: The probability threshold for classifying a token as noise.
    """
    return LANG_DETECTION_THRESHOLDS.get(str(lang), DEFAULT_DETECTION_THRESHOLD)


class AnomalyDetector:
    """Binary token classification wrapper for identifying non-standard social media words.

    Leverages pre-trained or fine-tuned XLM-RoBERTa token classification models
    to output noise probabilities for each token and classify them accordingly.

    Attributes:
        tokenizer (AutoTokenizer): Pre-trained XLM-RoBERTa tokenizer instance.
        model (AutoModelForTokenClassification): PyTorch model initialized for token classification (2 classes).
    """

    def __init__(self, model_checkpoint: str = "xlm-roberta-base") -> None:
        """Initializes the AnomalyDetector with tokenizer and model configurations.

        Args:
            model_checkpoint: Path to local model weight folder or Hugging Face hub identifier.
        """
        self.tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = AutoModelForTokenClassification.from_pretrained(
            model_checkpoint, num_labels=2
        ).to(device)

    def align_labels_with_tokens(self, labels: List[int], word_ids: List[Union[int, None]]) -> List[int]:
        """Aligns sequence-level labels with model subwords after tokenization.

        Assigns the original label to the first subword token of each word,
        and applies a dummy index (-100) to all subsequent subword pieces to
        properly ignore them during backward loss computations.

        Args:
            labels: List of label integers aligned with original words.
            word_ids: Word mapping indexes generated by the tokenizer.

        Returns:
            List[int]: Aligned labels matching tokenizer subword indices.
        """
        new_labels = []
        current_word = None
        for word_id in word_ids:
            if word_id != current_word:
                current_word = word_id
                label = -100 if word_id is None else labels[word_id]
                new_labels.append(label)
            else:
                new_labels.append(-100)
        return new_labels

    def prepare_data(self, raw_tokens: List[str], norm_tokens: List[str]) -> Tuple[Dict[str, Any], List[int]]:
        """Processes and aligns raw and normalized text pairs for model training.

        Compares raw and normalized tokens to generate binary classification targets,
        tokenizes the raw words, and aligns labels to tokenizer subwords.

        Args:
            raw_tokens: List of original social media words.
            norm_tokens: List of correct/normalized words.

        Returns:
            Tuple[Dict[str, Any], List[int]]: Tokenized inputs dictionary and aligned subword labels list.
        """
        labels = [0 if r == n else 1 for r, n in zip(raw_tokens, norm_tokens)]
        tokenized_inputs = self.tokenizer(raw_tokens, is_split_into_words=True, truncation=True)
        word_ids = tokenized_inputs.word_ids()
        aligned_labels = self.align_labels_with_tokens(labels, word_ids)
        return tokenized_inputs, aligned_labels

    def train_model(self, train_dataset: Any, eval_dataset: Any, output_dir: str = "./detection_model") -> None:
        """Fine-tunes the token classification model on training datasets.

        Args:
            train_dataset: Pre-processed PyTorch dataset for training.
            eval_dataset: Pre-processed PyTorch dataset for evaluation.
            output_dir: Path to directory where model checkpoint weights are saved.
        """
        data_collator = DataCollatorForTokenClassification(self.tokenizer)
        training_args = TrainingArguments(
            output_dir=output_dir,
            eval_strategy="epoch",
            learning_rate=2e-5,
            per_device_train_batch_size=16,
            num_train_epochs=3,
            weight_decay=0.01,
            save_strategy="epoch",
            logging_steps=50,
        )
        trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            processing_class=self.tokenizer,
            data_collator=data_collator,
        )
        trainer.train()
        trainer.save_model(output_dir)

    def predict_proba(self, sentence_tokens: List[str]) -> List[float]:
        """Calculates the noise probability for each word in a single sentence.

        Args:
            sentence_tokens: List of space-delimited words representing an input sentence.

        Returns:
            List[float]: Probability of each original word being a non-standard token (0.0 to 1.0).
        """
        tokenized_inputs = self.tokenizer(sentence_tokens, is_split_into_words=True, return_tensors="pt")
        word_ids = tokenized_inputs.word_ids()
        tokenized_inputs = {k: v.to(self.model.device) for k, v in tokenized_inputs.items()}

        self.model.eval()
        with torch.no_grad():
            outputs = self.model(**tokenized_inputs)

        probs = F.softmax(outputs.logits, dim=-1).squeeze()
        if probs.dim() == 1:
            probs = probs.unsqueeze(0)

        # Retrieve probability values for Class 1 (non-standard token)
        noise_probs = probs[:, 1].tolist()

        # Gather probability scores corresponding to the start of each word
        word_probabilities: List[float] = []
        current_word = None
        for idx, word_id in enumerate(word_ids):
            if word_id is None:
                continue
            if word_id != current_word:
                word_probabilities.append(noise_probs[idx])
                current_word = word_id
        return word_probabilities

    def predict_proba_batch(
        self,
        batch_tokens: Sequence[Sequence[str]],
        batch_size: int = 16,
        max_length: int = 512,
    ) -> List[List[float]]:
        """Performs batch probability predictions across multiple sentences.

        Calculates the probability distribution of class 1 for each subword token,
        merges values back to word-level spans, and pads truncated tokens.

        Args:
            batch_tokens: Sequence of input sentences, each representing a sequence of words.
            batch_size: Size of batches sent to the classification model.
            max_length: Truncation threshold to prevent GPU out-of-memory errors.

        Returns:
            List[List[float]]: Nested list containing noise probabilities corresponding to each word.
        """
        self.model.eval()
        all_word_probs: List[List[float]] = []
        with torch.no_grad():
            for start in range(0, len(batch_tokens), batch_size):
                chunk = [list(t) for t in batch_tokens[start:start + batch_size]]
                enc = self.tokenizer(
                    chunk, is_split_into_words=True, return_tensors="pt",
                    padding=True, truncation=True, max_length=max_length,
                )
                enc_dev = {k: v.to(self.model.device) for k, v in enc.items()}
                logits = self.model(**enc_dev).logits
                noise = F.softmax(logits, dim=-1)[:, :, 1].cpu().tolist()  # Dimension: (B, T)
                
                for b in range(len(chunk)):
                    word_ids = enc.word_ids(b)
                    word_probs: List[float] = []
                    current_word = None
                    for idx, word_id in enumerate(word_ids):
                        if word_id is None:
                            continue
                        if word_id != current_word:
                            word_probs.append(noise[b][idx])
                            current_word = word_id
                    
                    # Pad truncated words with a safe default probability (0.0: standard)
                    while len(word_probs) < len(chunk[b]):
                        word_probs.append(0.0)
                    all_word_probs.append(word_probs)
        return all_word_probs

    def predict_labels(
        self,
        batch_tokens: Sequence[Sequence[str]],
        batch_langs: Sequence[str],
        batch_size: int = 16,
        max_length: int = 512,
        threshold: float | None = None,
    ) -> List[List[int]]:
        """Performs batch predictions and applies thresholds to generate binary labels.

        Args:
            batch_tokens: Sequence of input sentences, each containing a sequence of word strings.
            batch_langs: Sequence of language strings matching each sentence.
            batch_size: Inference batch processing size.
            max_length: Model sequence length boundary.
            threshold: Custom threshold to override language-specific configs (None uses get_lang_threshold).

        Returns:
            List[List[int]]: Binary label predictions where 1 is non-standard and 0 is standard.
        """
        probs = self.predict_proba_batch(batch_tokens, batch_size=batch_size, max_length=max_length)
        labels: List[List[int]] = []
        for row_probs, lang in zip(probs, batch_langs):
            thr = get_lang_threshold(lang) if threshold is None else threshold
            labels.append([1 if p >= thr else 0 for p in row_probs])
        return labels
